name: CI - Push request - Ubuntu

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Clone sap-resources Repository
      env:
        RESOURCE_REPO: ${{ secrets.RESOURCE_REPO }}
      run: |
        mkdir sap-resources
        git clone ${RESOURCE_REPO} sap-resources
    - name: Build with Maven
      run: mvn -Dsap.lib.dir=sap-resources/wso2-sap-resources/resources/lib clean install
